@startuml Cas_d_utilisation
scale 1
Left to right direction
skinparam packageStyle rect
actor utilisateur

rectangle utilisation{
(utilisateur) -- (ajouter un commentaire)
(utilisateur) -- (authentification)
(ajouter un commentaire) ..> (authentification)

(utilisateur) -- (utiliser le formulaire de contact)
(utilisateur) -- (voir la liste des articles)
(utilisateur) -- (lire un article)

(authentification) ..> (créer un compte) :extend
}
@endumlmodération-des-commentaires
