version: '3'
services:
    traefik:
        container_name: traefik
        image: traefik:1.7.4-alpine
        restart: always
        depends_on:
          - web
        command: --docker
        ports:
          - 80:80
          - 443:443
        labels:
          - traefik.backend=traefik
          - traefik.frontend.rule=Host:monitor.localhost
          - traefik.port=8080
        networks:
          - proxy
          - internal
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - $PWD/traefik.toml:/traefik.toml
          - $PWD/acme.json:/acme.json

    web:
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysqldb
        labels:
          - traefik.backend=web
          - traefik.frontend.rule=Host:localhost
          - traefik.port=80
        networks:
          - internal

    php:
        image: nanoninja/php-fpm:${PHP_VERSION}
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./web:/var/www/html"
        networks:
            - internal
        labels:
            - traefik.enable=false

    composer:
        image: "composer"
        volumes:
            - "./web/app:/app"
        command: install
        networks:
            - internal
        labels:
            - traefik.enable=false
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb
        labels:
            - traefik.backend=phpmyadmin
            - traefik.frontend.rule=Host:pma.localhost
            - traefik.port=80
        networks:
            - internal

    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8989:3306"
        volumes:
            - "./database/mysql:/var/lib/mysql"
        networks:
            - internal
        labels:
            - traefik.enable=false

networks:
    proxy:
        external: false
    internal:
