@startuml sequence utilisateur 
actor       visiteur    as Foo1
boundary    systeme    as Foo2
database    database    as Foo3

Foo1 -> Foo2 : arrive sur le site
Foo2 -> Foo3 : requete de la page
Foo3 -> Foo2 : envoie de la page
Foo2 --> Foo1 : affichadge de la page à l'utilisateur
Foo1 -> Foo2 : register(): créer un utilisateur
Foo2 -> Foo3 : creation de l'utilisateur
Foo3 -> Foo2 : utilisateur créé
Foo2 --> Foo1 : vers la page de l'utilisateur
Foo1 -> Foo2 :login(): connection de l'utilisateur
Foo2 -> Foo3 : recherche de l'utilisateur
alt utlisateur trouvé
    Foo3 --> Foo2 : utilisateur trouvé
    Foo2 --> Foo1 : authentification reussie
    alt laisser un commentaire
        Foo1 -> Foo2 : écrire un commentaire
        Foo2 -> Foo3 : envoie du commentaire pour moderation
        Foo3 -> Foo2 : commentaire envoyé
        Foo2 --> Foo1 : confirmation de l' envoie
    end
else utilisateur non trouvé
    Foo3 --> Foo2 : utilisateur non trouvé
    Foo2 --> Foo1 : authentification echoué
end
@enduml